      SUBROUTINE XERMSG (LIBRAR, SUBROU, MESSG, NERR, LEVEL)
      CHARACTER*(*) LIBRAR, SUBROU, MESSG
      INTEGER NERR, LEVEL
      INTEGER NXERR
      COMMON /XFLAG/ NXERR
      SAVE /XFLAG/
      NXERR = NXERR + 1
      WRITE(0,*) 'XERMSG ', SUBROU, ' ', MESSG
      IF (LEVEL .GE. 2) STOP 1
      RETURN
      END
