      DOUBLE PRECISION FUNCTION D1MACH (I)
      INTEGER I
      IF (I .EQ. 1) D1MACH = TINY(1.0D0)
      IF (I .EQ. 2) D1MACH = HUGE(1.0D0)
      IF (I .EQ. 3) D1MACH = EPSILON(1.0D0)/RADIX(1.0D0)
      IF (I .EQ. 4) D1MACH = EPSILON(1.0D0)
      IF (I .EQ. 5) D1MACH = LOG10(DBLE(RADIX(1.0D0)))
      RETURN
      END
      INTEGER FUNCTION I1MACH (I)
      INTEGER I
      I1MACH = 0
      IF (I .EQ. 10) I1MACH = RADIX(1.0D0)
      IF (I .EQ. 14) I1MACH = DIGITS(1.0D0)
      RETURN
      END
      SUBROUTINE XERMSG (LIB, SUB, MSG, NERR, LEVEL)
      CHARACTER*(*) LIB, SUB, MSG
      INTEGER NERR, LEVEL
      RETURN
      END
