      SUBROUTINE XERMSG (LIBRAR, SUBROU, MESSG, NERR, LEVEL)
      CHARACTER*(*) LIBRAR, SUBROU, MESSG
      INTEGER NERR, LEVEL
      IF (LEVEL .GE. 2) THEN
        WRITE(*,*) 'XERMSG ', SUBROU, ' ', MESSG
        STOP 1
      END IF
      RETURN
      END
